### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by mcepl**
- I don't know why CRLF end of `.vim` breaks vim on Linux, but it does.
- Why not to add `ftdetect` script as well to make things more automagic.

### CODE REVIEW

**Comment by mcepl** [comment]
Damn, it is a duplicate of #1.

**Comment by johnsyweb** [comment]
Yeah. It's a shame I can't get #1 merged :-(

**Comment by mcepl** [comment]
Why not to contact Lubomír Husar (http://www.vim.org/account/profile.php?user_id=7258) and fork and take over the script (including on www.vim.org)? If there is a proper `Git{hub,lab}` repo, then the bloody unmaintained @vim-scripts can go to ...

**Comment by johnsyweb** [comment]
I tried two email addresses for Lubomír Husar but got NDRs for both (see my description for #1).

**Comment by mcepl** [comment]
OK, then I would just fork. You may try to contact vimonline people at http://vimonline.sourceforge.net/ (or possibly file a ticket at https://sourceforge.net/p/vimonline/bugs/) to take over the script officially.

**Pull request closed without merging**
